# Generated by Django 5.0.6 on 2024-07-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_listing_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='telephone_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=None, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
