# Generated by Django 5.0.7 on 2024-07-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_listing_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='media/listings/'),
        ),
    ]
