# Generated by Django 5.0.7 on 2024-07-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_alter_listing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='listings/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='slug',
            field=models.SlugField(default=None, null=True, unique=True),
        ),
    ]
